version: '3.4'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    #    volumes:
    #      - ../keycloak/build/libs:/opt/jboss/keycloak/standalone/deployments/
    #      - ./keycloak/imports:/opt/jboss/keycloak/imports
    command: ["-Dkeycloak.import=/opt/jboss/keycloak/imports/my-realm.json "]
    #   command: ["-Dkeycloak.migration.action=export -Dkeycloak.migration.provider=singleFile \
    #    -Dkeycloak.migration.realmName=crud-realm \
    #              -Dkeycloak.migration.file=/opt/jboss/keycloak/imports/crud-realm.json \
  ]

    ports:
      - "9990:9990"

  classicmodels-crud:
    container_name: classicmodels
    image: classicmodels-crud:latest
    environment:
      DB_HOST: database
    depends_on:
      - database

  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'classicmodels'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'my-secret-pw'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'my-secret-pw'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'